title: Jorge Guerra
url: "https://jorgeoguerra.github.io"
baseurl: "/"

markdown: kramdown

footer: no

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "guerra_jorge_cv.pdf"
 - name: "Contact"
   link: "contact"
